### ISSUE TITLE
Include simple examples 

### ISSUE THREAD

**Issue by macsupport** [nix23/gridifier#1]
Looks great and a tremendous amount of work but it would be helpful to include some simple examples or at least some links to codepens, etc rather than only the tests. It would make the install, use and setup more user friendly for novices. I would pay the developer license if the learning curve was a bit less steep.
Great work!

**Comment by nix23** [comment]
Thanks for your response! Yeah, I'm currently working on big update and the first issue in TODO list is tutorials. First tutorials will cover some simplest use-case examples, like:
0) How install Gridifier;
1) How to create pinterest-alike grids;
2) How to sort/filter/drag simple grids with images/HTML elements;
3) etc...
In future updates I will cover more advanced examples, like real-time grids sync with modern frameworks.(Probably first such tutorial will use Angular per data sync)

Every example will contain detailed tutorial, demo page, as well as link to codepen example. To simplify library usage all examples will be also available in /tutorials folder in GIT repository. 

Current update will also contain 2 important functions:
1) All insert operations will be able to 'wait' while all images inside inserted items are loaded. (With 'resolveImages': true setting) -> Done.
2) All inserted items will be capable to remain maximum close to their original insert positions on browser viewport resizes. (This option will be useful to avoid item 'jumps' on resizes with responsive images) -> Currently working on this feature.

I will try to release first update ASAP, most likely in nearest 2 weeks.

**Comment by macsupport** [comment]
Thanks for the info! Looking forward to it. I will  buy a developer license once I can get a simple example to work, lol.
To illustrate the problem for me without a simple example:
 I set up a  test with the following code from your site and it fails,  with no console errors. Obviously I'm missing something but I have no clue.

```
 <div class="main-container">
            <div class="main wrapper clearfix">
       <div class="gridSelector">
    <div class="gridItem">1</div>
    <div class="gridItem">2</div>
      <div class="gridItem">3</div>
    <div class="gridItem">4</div>
      <div class="gridItem">5</div>
    <div class="gridItem">6</div>
</div>
               </div> <!-- #main -->
        </div> <!-- #main-container -->

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="jquery-2.1.3.min.js"><\/script>')</script>
        <script src="build/gridifier.min.js"></script>

        <script>
        var grid = $(".gridSelector");        
var asyncGrid = new Gridifier(grid, {
    // Wide used core settings
    "class": "gridItem", // default - data: "data-gridifier-item"
    //data: "data-myitem", // default - data: "data-gridifier-item"
    //query: "> a", // default - data: "data-gridifier-item"
    grid: "vertical", // default = "vertical"
    prepend: "mirrored", // default = "mirrored"
    append: "default", // default = "default"
    intersections: "yes", // default = "yes"
    align: "top", // default = "top(Vertical grid)|left(Horizontal grid)"
    sortDispersion: "disabled", // default = "disabled"
    sortDispersionValue: "200px",
    toggleDuration: 800, // default = 500
    coordsChangeDuration: 500, // default = 300
    toggleTransitionTiming: "cubic-bezier(0.550, 0.055, 0.675, 0.190)", // default = "ease"
    coordsChangeTransitionTiming: "cubic-bezier(0.550, 0.055, 0.675, 0.190)", // default = "ease"
    rotatePerspective: "500px", // default = "200px"
    rotateBackface: false, // default = true
    rotateAngles: [-180, -360], // default = [0, -180, 180, 0]
    gridTransformType: "fit", // default = "fit"
    gridTransformTimeout: 0, // default = 100
    dragifier: true, // default = false
    dragifierMode: "intersection", // default = "intersection"
    widthPtAntialias: 0.1, // default = 0
    heightPtAntialias: 0.1, // default = 0
    widthPxAntialias: 1, // default = 0
    heightPxAntialias: 1, // default = 0
    repackSize: 20, // default = gridItems.length
    // Less used core settings
    maxInsertionRange: 10000, // default = 3000
    resizeTimeout: 100, // default = null
    disableItemHideOnGridAttach: true|false, // default = false
    retransformQueueBatchSize: 100, // default = 12
    retransformQueueBatchTimeout: 0 // default = 25
});

```

**Comment by nix23** [comment]
``` javascript
$(document).ready(function() {
    var grid = $(".gridSelector");
    var asyncGrid = new Gridifier(grid, {
         "class": "gridItem",
         "dragifier": true
    });

    asyncGrid.append(asyncGrid.collectNew());
});
```

Shortly, when you are creating new Gridifier instance, you are just passing settings, which will be used during all future operations. So, just passing  class: "gridItem" option will not actually 'connect' any grid item to Gridifier. It is used to collect grid items in all future operations. (Like sort/filter or appendNew/prependNew)

Thus, to actually connect grid items to Gridifier, you should use one of insert operations:
http://gridifier.io/grids/insert-types
So, if you want insert items to vertical grid(default grid) from left to the right(default direction) and in the bottom direction(end of the grid) you should use append() function:

``` javascript
// You can select and pass jQuery collection of grid items per insert
1) asyncGrid.append($(".gridItem")); 
```

``` javascript
// Alternatively, you can use appendNew() function -> it will do the same thing as first one,
// except that it will select all grid items with 'gridItem' class automatically.
// (which was passed in constructor settings)
2) asyncGrid.appendNew(); 
```

Setting 'dragifier': true will make all grid items draggable with connection intersection(default) algorithm. So, drag will be registred when draggable item will intersect any other grid item center point.

One more thing: probably you will see all items for short moment after page load before item animation will start. (Will look like blink) To avoid this, you can add visibility: hidden rule to .gridItem class.

**Comment by macsupport** [comment]
thanks. That worked. Now on to filters...
